export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'
export const GET_ARTISTS = 'GET_ARTISTS'
export const ADD_ARTIST = 'ADD_ARTIST'
export const DELETE_ARTIST = 'DELETE_ARTIST'
export const ADD_ARTIST_FROM_PLAYLIST = 'ADD_ARTIST_FROM_PLAYLIST'
